// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzi9Y3ZiNnabH61vKxLVhW4KP-CySie20',
    appId: '1:1023280259929:web:5f8b58b27e95ba4d1aa248',
    messagingSenderId: '1023280259929',
    projectId: 'aplikasi-katalog-flutter-9f851',
    authDomain: 'aplikasi-katalog-flutter-9f851.firebaseapp.com',
    storageBucket: 'aplikasi-katalog-flutter-9f851.firebasestorage.app',
    measurementId: 'G-7Q0PX4L2LW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw9XVjQJzAqLWAjcFTxZ1otQ6UmmPYMks',
    appId: '1:1023280259929:android:e2f3fcc5a5cdb3001aa248',
    messagingSenderId: '1023280259929',
    projectId: 'aplikasi-katalog-flutter-9f851',
    storageBucket: 'aplikasi-katalog-flutter-9f851.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM2Cdv4Dzyv3ivrWPHOcK4N92TTuyzKl0',
    appId: '1:1023280259929:ios:493de8eda68cf5d31aa248',
    messagingSenderId: '1023280259929',
    projectId: 'aplikasi-katalog-flutter-9f851',
    storageBucket: 'aplikasi-katalog-flutter-9f851.firebasestorage.app',
    iosBundleId: 'com.example.kampus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCM2Cdv4Dzyv3ivrWPHOcK4N92TTuyzKl0',
    appId: '1:1023280259929:ios:493de8eda68cf5d31aa248',
    messagingSenderId: '1023280259929',
    projectId: 'aplikasi-katalog-flutter-9f851',
    storageBucket: 'aplikasi-katalog-flutter-9f851.firebasestorage.app',
    iosBundleId: 'com.example.kampus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzi9Y3ZiNnabH61vKxLVhW4KP-CySie20',
    appId: '1:1023280259929:web:be57f00b4ec9fea61aa248',
    messagingSenderId: '1023280259929',
    projectId: 'aplikasi-katalog-flutter-9f851',
    authDomain: 'aplikasi-katalog-flutter-9f851.firebaseapp.com',
    storageBucket: 'aplikasi-katalog-flutter-9f851.firebasestorage.app',
    measurementId: 'G-CNSRB299JG',
  );
}
